DOCSP-39405: kotlin v5.1 content
mongodb/docs-kotlin pull request #161
Opened 2024-06-20 19:33 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-kotlin/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging:
- [oidc](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-39405-v5.1-content/fundamentals/enterprise-auth/#std-label-kotlin-oidc)
- [connection options](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-39405-v5.1-content/fundamentals/connection/connection-options/#std-label-connection-options:~:text=serverMonitoringMode)
- [whats new](https://preview-mongodbrustagir.gatsbyjs.io/kotlin/DOCSP-39405-v5.1-content/whats-new/#std-label-kotlin-coroutine-version-5.1)

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-06-20 20:07 UTC, norareidy approved these changes
LGTM + a few suggestions!

2024-06-20 20:07 UTC, norareidy commented on source/fundamentals/enterprise-auth.txt
> +The following sections describe how to use the ``MONGODB-OIDC``
S: I don't think this needs to be monospaced, based on the other mentions of MONGODB-OIDC, Kerberos, LDAP
```suggestion
The following sections describe how to use the MONGODB-OIDC
```

2024-06-27 17:01 UTC, rozza requested changes
Just a kotlin bug then LGTM

2024-06-27 17:01 UTC, rozza commented on examples/src/test/kotlin/EnterpriseAuthTest.kt
> +            .withMechanismProperty("OIDC_CALLBACK") { Context context ->
This doesn't compile in Kotlin try: 

```suggestion
            .withMechanismProperty("OIDC_CALLBACK") { context: Context ->
```

2024-06-27 17:01 UTC, rozza commented on examples/src/test/kotlin/EnterpriseAuthTest.kt
> +            .withMechanismProperty("OIDC_CALLBACK") { Context context ->
This doesn't compile in Kotlin try:

```suggestion
            .withMechanismProperty("OIDC_CALLBACK") { context: Context ->
```

2024-06-28 16:00 UTC, merged