DOCSP-44902 TOC Relabel
mongodb/docs-kotlin pull request #179
Opened 2024-11-09 03:22 UTC by lindseymoore

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-kotlin/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-44902>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-11-11 15:43 UTC, mongoKart approved these changes
lgtm w/ suggestions

2024-11-11 15:43 UTC, mongoKart commented on source/fundamentals/builders.txt
> +   Updates </fundamentals/builders/updates>
Same suggestion as i made for Java

2024-11-11 15:43 UTC, mongoKart commented on source/fundamentals/crud.txt
> +   Write Operations </fundamentals/crud/write-operations>
S: Remove Operations

2024-11-11 15:43 UTC, mongoKart commented on source/usage-examples.txt
> +   Delete Operations </usage-examples/delete-operations>
S: Remove "Operations"

2024-11-13 21:11 UTC, sarahemlin requested changes
LGTM with Mike's changes

2024-11-21 15:40 UTC, sarahemlin approved these changes

2024-11-21 22:36 UTC, merged